spring:
  application:
    name: WebChat
  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: ${jdbc.driver}
  data:
    redis:
      host: ${redis.host}
      port: 6379
      password: ${redis.password}
      database: 0


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mulberry.WebChat.entity

server:
  address: 0.0.0.0
  port: 8080


custom:
  jwt:
    secret-key: ${jwt.secret-key}
    access-expire: 600000
    refresh-expire: 86400000
  oss:
    endpoint: ${oss.endpoint}
    bucket-name: ${oss.bucket-name}
    region: ${oss.region}
    access-key-id: ${oss.access-key-id}
    access-key-secret: ${oss.access-key-secret}
    url-expire: 43200
    file-expire: 518400