spring:
  application:
    name: WebChat
  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: ${jdbc.driver}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mulberry.WebChat.entity

server:
  address: 0.0.0.0
  port: 8080


custom:
  jwt:
    secret-key: ${jwt.secret-key}
    expiration: 1800000